// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MyFilmMVCV1.Models;

namespace MyFilmMVCV1.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.5");

            modelBuilder.Entity("MyFilmMVCV1.Model.Movie", b =>
                {
                    b.Property<int>("FilmID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("FilmCertificate")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("FilmDescription")
                        .HasColumnType("TEXT");

                    b.Property<string>("FilmImage")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("FilmPrice")
                        .HasColumnType("TEXT");

                    b.Property<string>("FilmTitle")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("ReleaseDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("Stars")
                        .HasColumnType("INTEGER");

                    b.HasKey("FilmID");

                    b.ToTable("Movies");
                });
#pragma warning restore 612, 618
        }
    }
}
